In [1]:
from magpie_control import ur5  
import numpy as np
import time

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
robot = ur5.UR5_Interface(provide_ft_sensor=False)
robot.start()

In [ ]:
# robot.toggle_teach_mode()

In [ ]:
# robot.start_ft_sensor(ip_address="192.168.0.6", poll_rate=100)
# robot.debug = False
# print(f"{robot.get_ft_data()=}")


robot.get_ft_data()=[0.0, 0.0, 0.5, -0.01799, -0.002, 0.003]


In [4]:
pose = robot.get_tcp_pose()
pose

array([[-1.000e+00, -7.485e-05, -6.443e-05, -2.498e-01],
       [-7.485e-05,  1.000e+00,  2.064e-05, -4.084e-01],
       [ 6.443e-05,  2.064e-05, -1.000e+00,  3.563e-01],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00]])

In [8]:
home = np.array([[-1, 0, 0, -0.337],
                 [ 0, 1, 0, -0.497],
                 [ 0, 0,-1,  0.302],
                 [ 0, 0, 0,  1.   ]])

In [11]:
robot.moveL(home)

In [10]:
new = home.copy()
for i in range(4):
    new[2][3] -= 0.05
    robot.moveL(new)
    time.sleep(2)
    print(robot.get_tcp_pose())


[[-1.000e+00  8.128e-05 -1.190e-04 -3.370e-01]
 [ 8.128e-05  1.000e+00 -3.045e-05 -4.970e-01]
 [ 1.190e-04 -3.046e-05 -1.000e+00  2.520e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
[[-1.000e+00  2.328e-05 -1.003e-04 -3.370e-01]
 [ 2.327e-05  1.000e+00  4.130e-05 -4.970e-01]
 [ 1.003e-04  4.129e-05 -1.000e+00  2.020e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
[[-1.000e+00  7.377e-05 -1.731e-04 -3.370e-01]
 [ 7.378e-05  1.000e+00 -4.613e-05 -4.970e-01]
 [ 1.731e-04 -4.614e-05 -1.000e+00  1.521e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
[[-1.000e+00  7.784e-05 -2.772e-06 -3.370e-01]
 [ 7.784e-05  1.000e+00 -5.149e-05 -4.970e-01]
 [ 2.768e-06 -5.149e-05 -1.000e+00  1.020e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
