In [1]:
from magpie_control import ur5  
import numpy as np
import time

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
robot = ur5.UR5_Interface(provide_ft_sensor=False)
robot.start()

In [ ]:
# robot.toggle_teach_mode()

In [ ]:
# robot.start_ft_sensor(ip_address="192.168.0.6", poll_rate=100)
# robot.debug = False
# print(f"{robot.get_ft_data()=}")


robot.get_ft_data()=[0.0, 0.0, 0.5, -0.01799, -0.002, 0.003]


In [23]:
pose = robot.get_tcp_pose()
pose

array([[-1.000e+00, -2.540e-05, -8.253e-05, -3.370e-01],
       [-2.539e-05,  1.000e+00, -6.100e-05, -4.970e-01],
       [ 8.253e-05, -6.100e-05, -1.000e+00,  1.120e-01],
       [ 0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00]])

In [26]:
# zero is at 0.072 on the z-axis
# 24cm from home to floor
home = np.array([[-1, 0, 0, -0.337],
                 [ 0, 1, 0, -0.497],
                 [ 0, 0,-1,  0.312],
                 [ 0, 0, 0,  1.   ]])

In [27]:
robot.moveL(home)

In [ ]:
new = home.copy()
# make sure r*inc <= 0.23
r = 4
inc = 0.05
for i in range(r):
    new[2][3] -= inc
    robot.moveL(new)
    time.sleep(2)
    print(robot.get_tcp_pose())


[[-1.000e+00  6.710e-06 -7.901e-05 -3.370e-01]
 [ 6.708e-06  1.000e+00  2.710e-05 -4.970e-01]
 [ 7.901e-05  2.710e-05 -1.000e+00  2.620e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
[[-1.000e+00 -2.748e-05 -1.279e-04 -3.370e-01]
 [-2.748e-05  1.000e+00  1.617e-06 -4.970e-01]
 [ 1.279e-04  1.621e-06 -1.000e+00  2.120e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
[[-1.000e+00  1.062e-04 -7.966e-05 -3.370e-01]
 [ 1.062e-04  1.000e+00 -4.659e-05 -4.970e-01]
 [ 7.966e-05 -4.660e-05 -1.000e+00  1.620e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
[[-1.000e+00 -8.531e-05 -6.180e-06 -3.370e-01]
 [-8.531e-05  1.000e+00 -6.837e-05 -4.970e-01]
 [ 6.186e-06 -6.837e-05 -1.000e+00  1.120e-01]
 [ 0.000e+00  0.000e+00  0.000e+00  1.000e+00]]
