In [1]:
from magpie_control import ur5  
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
robot = ur5.UR5_Interface()
robot.start()

In [13]:
robot.toggle_teach_mode()

In [7]:
pose_1 = np.array([[-0.582,  0.812, -0.048, -0.249],
          [ 0.813,  0.582, -0.004, -0.395],
          [ 0.025, -0.041, -0.999,  0.263],
          [ 0.   ,  0.   ,  0.   ,  1.   ]])
pose_2 = np.array([[-0.582,  0.812, -0.048, -0.249],
          [ 0.813,  0.582, -0.004, -0.395],
          [ 0.025, -0.041, -0.999,  0.463],
          [ 0.   ,  0.   ,  0.   ,  1.   ]])
pose_3 = np.array([[-0.582,  0.812, -0.048, -0.307],
       [ 0.813,  0.582, -0.004, -0.314],
       [ 0.025, -0.041, -0.999,  0.466],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])

pose_precision_prep = np.array([
[-0.988, -0.142,  0.061, -0.328],
[-0.11,   0.37,  -0.923, -0.381],
[ 0.109, -0.918, -0.381,  0.157],
[ 0.,     0. ,    0. ,    1.   ]])
pose_precision_end = np.array([
[-0.988, -0.142,  0.061, -0.328],
[-0.11,   0.37,  -0.923, -0.381],
[ 0.109, -0.918, -0.381,  0.300],
[ 0.,     0. ,    0. ,    1.   ]])

pose_tripod_prep = np.array([
[-0.991, -0.099,  0.091, -0.331],
[-0.13,   0.538, -0.833, -0.404],
[ 0.034, -0.837, -0.546,  0.194],
[ 0.,     0.,     0.,     1.   ]])

pose_tripod_end = np.array([
[-0.991, -0.099,  0.091, -0.331],
[-0.13,   0.538, -0.833, -0.404],
[ 0.034, -0.837, -0.546,  0.300],
[ 0.,     0.,     0.,     1.   ]])

pose_tripod_shake = np.array([
[-0.991, -0.099,  0.091, -0.331],
[-0.13,   0.538, -0.833, -0.404],
[ 0.034, -0.837, -0.546,  0.350],
[ 0.,     0.,     0.,     1.   ]])


In [ ]:
# Step 0: move to home
# robot.moveL(pose_precision_prep)
# robot.moveL(pose_tripod_prep)

In [ ]:
# Step 1: move to grasp
# robot.moveL(pose_precision_end)
# robot.moveL(pose_tripod_end)

In [ ]:
# Step 2: move back to home
robot.moveL(pose_2, linSpeed=0.5, linAccel=0.75)

In [8]:
# Step 3: shake back and forth
for _ in range(2):
    robot.moveL(pose_tripod_end, linSpeed=0.5, linAccel=0.75, asynch=False)
    robot.moveL(pose_tripod_shake, linSpeed=0.5, linAccel=0.75, asynch=False)

In [22]:
pose = robot.get_tcp_pose()
# robot.moveL_delta([0.1, 0.0, 0], frame='wrist')
# robot.toggle_teach_mode()
# robot.moveL(pose_1)
print(pose)

[[-0.961 -0.236  0.144 -0.367]
 [-0.216  0.315 -0.924 -0.438]
 [ 0.172 -0.919 -0.354  0.237]
 [ 0.     0.     0.     1.   ]]
