In [1]:
from magpie_control import ur5  
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
robot = ur5.UR5_Interface(provide_ft_sensor=True)
robot.debug = True
robot.start()

In [ ]:
robot.start_ft_sensor(ip_address="192.168.0.5", poll_rate=100)
print(f"{robot.get_ft_data()=}")
force = np.array([0, 2, -3])
goal_delta = np.array([0, 0, 0.09])
wrench_goal = np.hstack((force, np.zeros(3)))
init_cmd = np.hstack((force / -300, np.zeros(3)))
duration = 3
max_force = 5.0 # maximum force in Newtons
P = 0.004 # stiffness gain, default is 0.0005 <--play with this for compliance sensitivity
robot.force_position_control(wrench=wrench_goal, init_cmd=init_cmd, goal_delta=goal_delta, 
                             duration=duration, max_force=max_force, p=P, tolerance=0.015)


robot.get_ft_data()=[0.3, 0.2, 0.2, -0.005, 0.004, 0.004]
Starting force-position control with goal delta [0.   0.   0.09], max force 5.0 N
Initial Distance to goal: 0.0900 m
Initial FT: [0.3, 0.4, 0.3, -0.021, 0.012, 0.00899], Goal FT: [ 0.  2. -3.  0.  0.  0.]
Initial Speed Command (wrist frame): [-0.    -0.007  0.01   0.     0.     0.   ]
Distance to goal: 0.0900 m
Current FT: [0.3, 0.4, 0.3, -0.021, 0.012, 0.00899], Goal FT: [ 0.  2. -3.  0.  0.  0.]
Current Speed Command (wrist frame): [-0.    -0.007  0.01   0.     0.     0.   ]
Distance to goal: 0.0900 m
Current FT: [0.7, 0.4, 0.1, -0.008, 0.013, 0.013], Goal FT: [ 0.  2. -3.  0.  0.  0.]
Current Speed Command (wrist frame): [ 0.    -0.007  0.01  -0.    -0.    -0.   ]
Distance to goal: 0.0900 m
Current FT: [0.8, 0.4, -0.1, -0.016, 0.03, 0.02], Goal FT: [ 0.  2. -3.  0.  0.  0.]
Current Speed Command (wrist frame): [-0.    -0.007  0.01   0.     0.     0.   ]
Distance to goal: 0.0900 m
Current FT: [0.7, 0.5, 0.9, -0.027, 0.01899, 0

In [3]:
robot.toggle_teach_mode()

In [21]:
pose_1 = np.array([[-0.582,  0.812, -0.048, -0.249],
          [ 0.813,  0.582, -0.004, -0.395],
          [ 0.025, -0.041, -0.999,  0.263],
          [ 0.   ,  0.   ,  0.   ,  1.   ]])
pose_2 = np.array([[-0.582,  0.812, -0.048, -0.249],
          [ 0.813,  0.582, -0.004, -0.395],
          [ 0.025, -0.041, -0.999,  0.463],
          [ 0.   ,  0.   ,  0.   ,  1.   ]])
pose_3 = np.array([[-0.582,  0.812, -0.048, -0.307],
       [ 0.813,  0.582, -0.004, -0.314],
       [ 0.025, -0.041, -0.999,  0.466],
       [ 0.   ,  0.   ,  0.   ,  1.   ]])

pose_precision_prep = np.array([
    [-0.999,  0.005,  -0.034, -0.431],
    [ 0.033,  0.346,  -0.938, -0.390],
    [ 0.007, -0.938,  -0.346,  0.183],
    [ 0.,     0. ,    0. ,    1.   ]
], dtype=float)

pose_precision_end = np.array([
    [-0.999,  0.005,  -0.034, -0.431],
    [ 0.033,  0.346,  -0.938, -0.390],
    [ 0.007, -0.938,  -0.346,  0.300],
    [ 0.,     0. ,    0. ,    1.   ]
], dtype=float)

pose_precision_shake = np.array([
    [-0.333,  0.943, -0.029, -0.431],
    [ 0.342,  0.091, -0.935, -0.390],
    [ -0.879, -0.321, -0.353,  0.300],
    [ 0.,     0. ,    0. ,    1.   ]
], dtype=float)

# [[-0.333  0.943 -0.029 -0.43 ]
#  [ 0.342  0.091 -0.935 -0.389]
#  [-0.879 -0.321 -0.353  0.3  ]
#  [ 0.     0.     0.     1.   ]]

pose_tripod_prep = np.array([
    [-0.993,  0.091, -0.071, -0.373],
    [ 0.112,  0.621, -0.776, -0.366],
    [-0.026, -0.779, -0.627,  0.275],#close to table 0.246, now higher
    [ 0.,     0.,     0.,     1.   ]
], dtype=float)

pose_tripod_end = np.array([
    [-0.993,  0.091, -0.071, -0.373],
    [ 0.112,  0.621, -0.776, -0.366],
    [-0.026, -0.779, -0.627,  0.400],
    [ 0.,     0.,     0.,     1.   ]
], dtype=float)

pose_tripod_shake = np.array([
    [-0.286,  0.956, -0.065, -0.373],
    [ 0.62,  0.133, -0.773, -0.366],
    [-0.73, -0.262, -0.631,  0.400],
    [ 0.,     0.,     0.,     1.   ]
], dtype=float)
# [[-0.286  0.956 -0.065 -0.376]
#  [ 0.62   0.133 -0.773 -0.367]
#  [-0.73  -0.262 -0.631  0.395]
#  [ 0.     0.     0.     1.   ]]

In [ ]:
# Step 0: move to home
# robot.moveL(pose_precision_prep)
# robot.moveL(pose_tripod_prep)

In [ ]:
# Step 1: move to grasp
# robot.moveL(pose_precision_end)
# robot.moveL(pose_tripod_end)

In [57]:
pose_peg_prep = np.array([
    [-0.999, -0.019, -0.041, -0.448],
    [ 0.026,  0.499, -0.866, -0.473],
    [ 0.037, -0.867, -0.498,  0.243],
    [ 0.    , 0.    , 0.    , 1.   ]
 ], dtype=float)

pose_peg_go = np.array([
    [-0.999, -0.019, -0.041, -0.448],
    [ 0.026,  0.499, -0.866, -0.493],
    [ 0.037, -0.867, -0.498,  0.243],
    [ 0.    , 0.    , 0.    , 1.   ]
 ], dtype=float)

pose_peg_n = np.array([
    [-0.999, -0.019, -0.041, -0.448],
    [ 0.026,  0.499, -0.866, -0.487],
    [ 0.037, -0.867, -0.498,  0.243],
    [ 0.    , 0.    , 0.    , 1.   ]
 ], dtype=float)

pose_peg_lift = np.array([
    [-0.999, -0.019, -0.041, -0.448],
    [ 0.026,  0.499, -0.866, -0.487],
    [ 0.037, -0.867, -0.498,  0.303],
    [ 0.    , 0.    , 0.    , 1.   ]
 ], dtype=float)

pose_peg_put = np.array([
    [-0.999, -0.019, -0.041, -0.448],
    [ 0.026,  0.499, -0.866, -0.487],
    [ 0.037, -0.867, -0.498,  0.243],
    [ 0.    , 0.    , 0.    , 1.   ]
 ], dtype=float)

In [56]:
# Step 2: move back to home
robot.moveL(pose_peg_put, linSpeed=0.5, linAccel=0.75)

In [22]:
# Step 3: shake back and forth
for _ in range(2):
    robot.moveL(pose_tripod_end, linSpeed=1, linAccel=5, asynch=False)
    robot.moveL(pose_tripod_shake, linSpeed=1, linAccel=5, asynch=False)

In [4]:
pose = robot.get_tcp_pose()
# robot.moveL_delta([0.1, 0.0, 0], frame='wrist')
# robot.toggle_teach_mode()
# robot.moveL(pose_1)
print(pose)

[[-0.988 -0.142  0.061 -0.328]
 [-0.11   0.37  -0.922 -0.381]
 [ 0.109 -0.918 -0.381  0.3  ]
 [ 0.     0.     0.     1.   ]]


In [6]:
pose = robot.get_tcp_pose()
print(pose)

[[-0.996 -0.059 -0.062 -0.439]
 [ 0.023  0.509 -0.86  -0.493]
 [ 0.083 -0.858 -0.506  0.252]
 [ 0.     0.     0.     1.   ]]
